const isVowelSandwich = require("../vowelSandwich");

const data = [
  ["cat", true],
  ["ear", false],
  ["bake", false],
  ["fai", false],
  ["eik", false],
  ["nel", true],
  ["lea", false],
  ["rur", true],
  ["zuh", true],
  ["iiq", false],
  ["eir", false],
  ["niv", true],
  ["xap", true],
  ["xuqrc", false],
  ["rvp", false],
  ["suj", true],
  ["aeo", false],
  ["nay", true],
  ["cis", true],
  ["leb", true],
  ["aux", false],
  ["vii", false],
  ["faz", true],
  ["taf", true],
  ["fek", true],
  ["tig", true],
  ["hof", true],
  ["yiy", true],
  ["ray", true],
  ["e", false],
  ["oot", false],
  ["oel", false],
  ["cip", true],
  ["faw", true],
  ["kow", true],
  ["ter", true],
  ["qid", true],
  ["mix", true],
  ["eoo", false],
  ["fan", true],
  ["zoc", true],
  ["rf", false],
  ["adt", false],
  ["sao", false],
  ["yur", true],
  ["bow", true],
  ["aez", false],
  ["sud", true],
  ["nacr", false],
  ["phlsf", false],
  ["iah", false],
  ["to", false],
  ["lib", true],
  ["oiu", false],
  ["uaw", false],
  ["zaw", true],
  ["sow", true],
  ["iok", false],
  ["xoa", false],
  ["lof", true],
  ["suq", true],
  ["sev", true],
  ["hek", true],
  ["ryxkk", false],
  ["csgt", false],
  ["rig", true],
  ["rur", true],
  ["luv", true],
  ["rou", false],
  ["kuy", true],
  ["kax", true],
  ["qnran", false],
  ["aoi", false],
  ["uis", false],
  ["dey", true],
  ["tia", false],
  ["dawjq", false],
  ["bjt", false],
  ["rag", true],
  ["iee", false],
  ["gic", true],
  ["iui", false],
  ["rap", true],
  ["qer", true],
  ["qiv", true],
  ["dod", true],
  ["hom", true],
  ["eio", false],
  ["xea", false],
  ["voo", false],
  ["res", true],
  ["zeq", true],
  ["rol", true],
  ["pee", false],
  ["iee", false],
  ["rig", true],
  ["eow", false],
  ["oey", false],
  ["pux", true],
  ["sij", true],
  ["tak", true],
  ["uim", false],
  ["zia", false]
];

describe("isVowelSandiwch", () => {
  describe("Return boolean if a three string word is a vowel sandwich", () => {
    test.each(data)("isVowelSandwich(%p) = %s", (str, result) => {
      let actual = isVowelSandwich(str);

      expect(actual).toEqual(result);
    });
  });
});
